name: Periodic
on:
  push:
  schedule:
    - cron: 10 * * * *
jobs:
  import_events:
    name: Import events from HydroQuebec
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: 'requirements.txt'
    - run: pip install -r requirements.txt
    - name: Import events
      run: ./hydroquebec_peak_events_ical.py
    - name: Check for modified files
      id: git-check
      run: echo modified=$(if [ -n "$(git status --porcelain data)" ]; then echo "true"; else echo "false"; fi) >> $GITHUB_OUTPUT
    - name: Commit events
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add data
        git commit -m "Import events from HydroQuebec"
        git push
